jdk: oraclejdk11
script:
  - cd src
  - javac -Xlint:unchecked *.java
  - java Populate
  - java Main < ../Scenari/admin_scenario.txt
  - java Main < ../Scenari/new_account_scenario.txt
  - java Main < ../Scenari/log_scenario.txt
  - java Main < ../Scenari/rent_return_classic_scenario.txt
  - java Main < ../Scenari/new_sub_scenario.txt
  - java Main < ../Scenari/rent_return_sub_scenario.txt
  - java Main < ../Scenari/create_slavecard_scenario.txt
  - java Main < ../Scenari/managed_slave_card.txt
  - java Main < ../Scenari/slave_scenario.txt

